var bonitaEvents = {
	day31 : '<div>TEST - THIS IS DAY 31 - Poker Early Bird until 1pm</div> <div>Poker High Hand 7pm-10pm</div>',
	day30 : '<div>Poker Early Bird until 1pm</div> <div>Poker High Hand 7pm-10pm</div>',
	day29 : '<div>Poker Early Bird until 1pm</div> <div>Poker High Hand 7pm-10pm</div>',
	day28 : '<div>Poker Early Bird until 1pm</div> <div>Poker High Hand 7pm-10pm</div>',
	day27 : '<div>Poker Early Bird until 1pm</div> <div>Poker High Hand 7pm-10pm</div>',
	day26 : '<div>Poker Early Bird until 1pm</div> <div>Poker High Hand 7pm-10pm</div>',
	day25 : '<div>Poker Early Bird until 1pm</div> <div>Poker High Hand 7pm-10pm</div>',
	day24 : '<div>Poker Early Bird until 1pm</div> <div>Poker High Hand 7pm-10pm</div>',
	day23 : '<div>Poker Early Bird until 1pm</div> <div>Poker High Hand 7pm-10pm</div>',
	day22 : '<div>Poker Early Bird until 1pm</div> <div>Poker High Hand 7pm-10pm</div>',
	day21 : '<div>Poker Early Bird until 1pm</div> <div>Poker High Hand 7pm-10pm</div>',
	day20 : '<div>Poker Early Bird until 1pm</div> <div>Poker High Hand 7pm-10pm</div>',
	day19 : '<div>Poker Early Bird until 1pm</div> <div>Poker High Hand 7pm-10pm</div>',
	day18 : '<div>Poker Early Bird until 1pm</div> <div>Poker High Hand 7pm-10pm</div>',
	day17 : '<div>TEST- THIS IS DAY 17 - Poker Early Bird until 1pm</div> <div>Poker High Hand 7pm-10pm</div>',
	day16 : '<div>Poker Early Bird until 1pm</div> <div>Poker High Hand 7pm-10pm</div>',
	day15 : '<div>Poker Early Bird until 1pm</div> <div>Poker High Hand 7pm-10pm</div>',
	day14 : '<div>Poker Early Bird until 1pm</div> <div>Poker High Hand 7pm-10pm</div>',
	day13 : '<div>Poker Early Bird until 1pm</div> <div>Poker High Hand 7pm-10pm</div>',
	day12 : '<div>Poker Early Bird until 1pm</div> <div>Poker High Hand 7pm-10pm</div>',
	day11 : '<div>Poker Early Bird until 1pm</div> <div>Poker High Hand 7pm-10pm</div>',
	day10 : '<div>Poker Early Bird until 1pm</div> <div>Poker High Hand 7pm-10pm</div>',
	day9 : '<div>Poker Early Bird until 1pm</div> <div>Poker High Hand 7pm-10pm</div>',
	day8 : '<div>Poker Early Bird until 1pm</div> <div>Poker High Hand 7pm-10pm</div>',
	day7 : '<div>Poker Early Bird until 1pm</div> <div>Poker High Hand 7pm-10pm</div>',
	day6 : '<div>Poker Early Bird until 1pm</div> <div>Poker High Hand 7pm-10pm</div>',
	day5 : '<div>Poker Early Bird until 1pm</div> <div>Poker High Hand 7pm-10pm</div>',
	day4 : '<div>Poker Early Bird until 1pm</div> <div>Poker High Hand 7pm-10pm</div>',
	day3 : '<div>Poker Early Bird until 1pm</div> <div>Poker High Hand 7pm-10pm</div>',
	day2 : '<div>Poker Early Bird until 1pm</div> <div>Poker High Hand 7pm-10pm</div>',
	day1 : '<div>TEST - THIS IS DAY 1 - Poker Early Bird until 1pm</div> <div>Poker High Hand 7pm-10pm</div>'
}